In [ ]:
#import necessary information
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split



In [ ]:
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


In [ ]:
path = '/drive/My Drive/Colab Notebooks/ODL Datas/boston.csv'
df = pd.read_csv(path)
df

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0    0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1    0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2    0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3    0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4    0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2
..       ...   ...    ...   ...    ...  ...    ...      ...     ...    ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  273.0     21.0  391.99   9.67   22.4
502  0.04527   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   9.08   20.6
503  0.06076   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   5.64   23.9
504  0.10959   0.0  11.93   0.0  0.573  ...  273.0     21.0  393.45   6.48   22.0
505  0.04741   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   7.88   11.9

[506 rows x 14 columns]

In [ ]:
df = pd.DataFrame(df)
x = df[['LSTAT','B','PTRATIO','TAX','RAD','DIS','AGE','RM','NOX','CHAS','INDUS','ZN','CRIM']].values.reshape(-1,13)

y = df['PRICE']

In [ ]:
x

array([[4.9800e+00, 3.9690e+02, 1.5300e+01, ..., 2.3100e+00, 1.8000e+01,
        6.3200e-03],
       [9.1400e+00, 3.9690e+02, 1.7800e+01, ..., 7.0700e+00, 0.0000e+00,
        2.7310e-02],
       [4.0300e+00, 3.9283e+02, 1.7800e+01, ..., 7.0700e+00, 0.0000e+00,
        2.7290e-02],
       ...,
       [5.6400e+00, 3.9690e+02, 2.1000e+01, ..., 1.1930e+01, 0.0000e+00,
        6.0760e-02],
       [6.4800e+00, 3.9345e+02, 2.1000e+01, ..., 1.1930e+01, 0.0000e+00,
        1.0959e-01],
       [7.8800e+00, 3.9690e+02, 2.1000e+01, ..., 1.1930e+01, 0.0000e+00,
        4.7410e-02]])

In [ ]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: PRICE, Length: 506, dtype: float64

In [ ]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm').set_precision(2)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 13)
(102, 13)
(404,)
(102,)


In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)

x_test_sc = sc.transform(x_test)

print(x_train_sc)

[[ 8.35287872e-01 -3.01968083e-04  1.17561917e+00 ... -4.02011945e-01
  -5.07766334e-01 -2.73809525e-01]
 [-1.32549534e+00  4.12907260e-01 -2.20285923e+00 ... -1.43188822e+00
   3.33136528e+00 -4.04895262e-01]
 [ 1.15819623e+00 -3.84927565e+00  8.10378266e-01 ...  1.07815655e+00
  -5.07766334e-01  8.07334818e+00]
 ...
 [ 7.28600090e-01  3.87833612e-01  3.53827130e-01 ... -1.71664438e-01
  -5.07766334e-01 -3.85985039e-01]
 [-2.14519905e-01  4.05598798e-01  7.98964487e-02 ... -3.79142727e-02
  -5.07766334e-01 -3.80138300e-01]
 [-9.82671938e-01  1.93878260e-01  1.63217031e+00 ... -1.32786031e+00
   2.90479510e+00 -3.94334229e-01]]


In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
model = LinearRegression()
model.fit(x_train_sc,y_train)

r2 = model.score(x_test_sc,y_test)
print('score %.4f'% r2)

score 0.7330


In [ ]:
model.intercept_

22.64678217821785

In [ ]:
model.coef_

array([-4.18194997,  1.0555622 , -2.08839243, -2.21339805,  3.1648605 ,
       -3.06782623,  0.03349123,  2.35818096, -1.83414619,  0.68765265,
        0.01027511,  1.15746305, -1.12987107])

In [ ]:
#sgdregressor
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error
model2 = SGDRegressor(random_state=10)
model2.fit(x_train_sc,y_train)

r2 = model2.score(x_test_sc,y_test)
print('r squared %.2f' % r2)
y_prediction = model2.predict(x_test)

MSE = mean_squared_error(y_test,y_prediction)
print("mean squared error: %.5f" % MSE)
print("coefficients:", model2.coef_)
print("y intercept:",model2.intercept_)

r squared 0.73
mean squared error: 135459.16751
coefficients: [-4.15939164  1.05897964 -2.04741026 -1.25020074  2.25520931 -2.97976088
 -0.03102452  2.42080174 -1.72639175  0.71894923 -0.33359462  1.05277026
 -1.07800179]
y intercept: [22.62408063]


In [ ]:
#GridSearchCV
from sklearn.model_selection import GridSearchCV

parameters={'loss':('squared_loss','huber'),'penalty':('l2','l1','elasticnet'),
            'alpha':[1e-6,1e-5,1e-4,1e-3,1e-2,1e-1,1],'max_iter':[1000,2000,5000]}

model3 = SGDRegressor()
clf = GridSearchCV(model3,parameters)
clf.fit(x_train_sc,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SGDRegressor(alpha=0.0001, average=False,
                                    early_stopping=False, epsilon=0.1,
                                    eta0=0.01, fit_intercept=True,
                                    l1_ratio=0.15, learning_rate='invscaling',
                                    loss='squared_loss', max_iter=1000,
                                    n_iter_no_change=5, penalty='l2',
                                    power_t=0.25, random_state=None,
                                    shuffle=True, tol=0.001,
                                    validation_fraction=0.1, verbose=0,
                                    warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [1e-06, 1e-05, 0.0001, 0.001, 0.01, 0.1, 1],
                         'loss': ('squared_loss', 'huber'),
                         'max_iter': [1000, 2000, 5000],
                         'penalty': ('l2

In [ ]:
clf.best_params_

{'alpha': 0.01, 'loss': 'squared_loss', 'max_iter': 1000, 'penalty': 'l2'}

In [ ]:
clf.best_score_

0.7052307818754497

In [ ]:
clf.best_estimator_.coef_

array([-4.09176095,  1.05477047, -2.02199454, -1.24918311,  2.21716242,
       -2.87955982, -0.04977752,  2.43527914, -1.64310614,  0.72465697,
       -0.31963251,  1.01921008, -1.06763812])

In [ ]:
clf.best_estimator_.intercept_

array([22.65474839])